{% set name = "pygraphviz" %}
{% set version = "1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  # For some reason there are no .gz files here
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: 411ae84a5bc313e3e1523a1cace59159f512336318a510573b47f824edef8860

build:
  number: 0
  # It is possible to add windows support, but the
  # graphviz win package is not ready for it yet
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - pkg-config
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - graphviz
  run:
    - python
    - graphviz

test:
  imports:
    - pygraphviz
    - pygraphviz.tests
  source_files:
    - pygraphviz/tests
  commands:
    - nosetests --verbosity=3 pygraphviz/tests
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]
  requires:
    - mock >=1.3
    - nose >=0.10.1

about:
  home: http://pygraphviz.github.io
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python interface to Graphviz
  description: |
    PyGraphviz is a Python interface to the Graphviz graph layout and
    visualization package. With PyGraphviz you can create, edit, read, write,
    and draw graphs using Python to access the Graphviz graph data structure
    and layout algorithms. PyGraphviz provides a similar programming
    interface to NetworkX (http://networkx.github.io).
  doc_url: https://graphviz.readthedocs.io
  dev_url: https://github.com/pygraphviz/pygraphviz

extra:
  recipe-maintainers:
    - nehaljwani
