appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: sLx5CQeat20C8P9xAOehfjU+wez+rb5g02b1AVZw9+SsPEuo10HmMM7iCq32JyS7NairVELSw/tEEyZ0Hyju0kUxlRk0BsRySWYCpxZ3NLBTxWnOhlL8dHYkqxm2f9ljr2m5pVENVpSYVx3q+wiVvbUjwbbZE+cmErpNMhLCyEf/B8OEa7ftnRwlo0Ac13PrIJGFbzpi5t+vqW4Vt6pQZsQPs8huBXA6Hnqrbb8tgUGwM/AYIMbkxjbiSFNGvxv8ZMsYv2aCwgk28hIR1valWqYDY8wYhkA6sjowr5T0d9+z5OkRuy3MJmNmniKJuFn/9mp9FR20MW+K2R5urm3HvjoSdp6ygAuGWPDEXlzEW2ZOHVRpBqnRlQ/bED6y7HvyTj2z5AjBLBUH2/n4t+l4GUO1O0zWiOSG/SEaFXNtRmR/qEfAI8qn6e6XbeED2fbQ9zxhRE2i/YfWz8vA0sUn848fUGWW6GLJA4AIyiIFn539mt4vcXex+irMZ5CrCtf00P2HC68AyD+wU/J6vVh51qOzj5zgFV83O8jm0NCuFBYEMsuLiHzSGphFwXBJKiGasTvCp9geYvfViXBy9hWIU2zaFWA7G2uArypXhuvVvQtJpqBvkPd058gqglKTVRFzwgbK7olH3DqRBubYJtWW8OOFqRmAVxL+qKMj/YPLo4g=}
